# Generated by Django 5.1.1 on 2024-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creaturename', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('mythology', 'Mythology'), ('books', 'Books'), ('comics', 'Comics'), ('videogames', 'Video Games'), ('tv', 'TV Shows'), ('movies', 'Movies')], max_length=20)),
                ('originname', models.CharField(max_length=100)),
            ],
        ),
    ]
